### ISSUE TITLE
Stange error: EACCES: permission denied, scandir '/home'

### ISSUE THREAD

**Issue by mcblum** [js-cli/js-liftoff#83]
Does anyone have any idea how I can indicated to liftoff that /home is protected so it should use /home/username as the route? We're trying to deploy our app and getting stuck at:

```
username@domain.com [~/www/test/domain.com]# gulp webpack
/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:283
      if (this.strict) throw er
                       ^

Error: EACCES: permission denied, scandir '/home'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at GlobSync._readdir (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:239:41)
    at GlobSync._processReaddir (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:109:22)
    at GlobSync._process (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:105:10)
    at new GlobSync (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:43:10)
    at Function.globSync [as sync] (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:22:10)
    at /usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/lib/findup-sync.js:31:19
    at Array.map (native)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/lib/findup-sync.js:30:22)
```

**Comment by tkellen** [comment]
Have you tried specifying a path to your gulpfile using the [`--gulpfile` flag](https://github.com/gulpjs/gulp-cli#flags)?

**Comment by tkellen** [comment]
cc @sttk btw, I believe this behavior is coming from http://github.com/js-cli/fined

**Comment by mcblum** [comment]
@tkellen I have not. I believe that js-liftoff is being pulled in as part of Webpack or maybe our Gulp component generators, so I'm not invoking it directly. If the task I'm running is `gulp webpack` which packages our files for deploy, would would I pass a path directly to a dependency?

Thank you for you assistance on this!

**Comment by tkellen** [comment]
Try running `gulp --gulpfile /path/to/gulpfile webpack`

**Comment by sttk** [comment]
@tkellen fined doesn't use findup-sync. gulp-cli (liftoff) uses it to find `gulpfile.js` (`configPath`) and gulp's `package.json`(`modulePackage`)  and these findings don't use fined.

**Comment by mcblum** [comment]
@tkellen I tried specifying the exact path and still got:

```
DEBUG [68fdcc3b]       /usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:283

      if (this.strict) throw er

                       ^



Error: EACCES: permission denied, scandir '/home'

    at Error (native)

    at Object.fs.readdirSync (fs.js:951:18)

    at GlobSync._readdir (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:239:41)

    at GlobSync._processReaddir (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:109:22)

    at GlobSync._process (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:105:10)

    at new GlobSync (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:43:10)

    at Function.globSync [as sync] (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/node_modules/glob/sync.js:22:10)

    at /usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/lib/findup-sync.js:31:19

    at Array.map (native)

    at module.exports (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/findup-sync/lib/findup-sync.js:30:22)
```

@tkellen I'm not 100% sure what that means. Am I posting in the wrong repo?

**Comment by mcblum** [comment]
Well, after trying 1000 things I finally realized that Gulp was installed globally on the server and simply needed to be updated to 3.9.1. I don't know why. Whatever it was, it works now!

Thanks all.

**Comment by phated** [comment]
@mcblum glad that fixed it.  Going to close this.
